# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bcopy < Formula
  desc "Bulk copy codebase files to clipboard with smart filtering in markdown format for feeding it to LLMs"
  homepage "https://github.com/nodelike/bcopy"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nodelike/bcopy/releases/download/v1.0.0/bcopy_Darwin_x86_64.tar.gz"
      sha256 "bd4bcb21006c4266e9f433c49e409c2e1eb93530f4ef03be4de411ea922f78f8"

      def install
        bin.install "bcopy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nodelike/bcopy/releases/download/v1.0.0/bcopy_Darwin_arm64.tar.gz"
      sha256 "18498ede1b2403413c0b05b6ff8366dcd378654558d8125f96622560d420067f"

      def install
        bin.install "bcopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nodelike/bcopy/releases/download/v1.0.0/bcopy_Linux_x86_64.tar.gz"
      sha256 "33ef92b5953a9161015a36418584e9becb71a9a666b8919119b7797b2e5d2d0b"
      def install
        bin.install "bcopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nodelike/bcopy/releases/download/v1.0.0/bcopy_Linux_arm64.tar.gz"
      sha256 "e867edb382e5b39acbc2a558e93e27298e2424dfba66658901a0baa7de3026e0"
      def install
        bin.install "bcopy"
      end
    end
  end

  test do
    system "#{bin}/bcopy", "--help"
  end
end
