# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bcopy < Formula
  desc "Bulk copy codebase files to clipboard with smart filtering in markdown format for feeding it to LLMs"
  homepage "https://github.com/nodelike/bcopy"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nodelike/bcopy/releases/download/v1.0.2/bcopy_Darwin_x86_64.tar.gz"
      sha256 "8a8606f9746865fcf64b7334eee37d9737591bb9e63616b0829a80f6800821ea"

      def install
        bin.install "bcopy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nodelike/bcopy/releases/download/v1.0.2/bcopy_Darwin_arm64.tar.gz"
      sha256 "234f34e10bdfd2837e0ca0b453ed3e76fd59133558a48a0d790d00f63a53e5c7"

      def install
        bin.install "bcopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nodelike/bcopy/releases/download/v1.0.2/bcopy_Linux_x86_64.tar.gz"
      sha256 "371afddb876e000792062d7ed089adf41151d656589928a25caf2672aa7536d9"
      def install
        bin.install "bcopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nodelike/bcopy/releases/download/v1.0.2/bcopy_Linux_arm64.tar.gz"
      sha256 "4a7c6fe05cb3ce37e1093a3b9ccdf01e81cad880f4e6948127017864a12b61d6"
      def install
        bin.install "bcopy"
      end
    end
  end

  test do
    system "#{bin}/bcopy", "--help"
  end
end
