# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffloc < Formula
  desc "Beautiful TUI for git diff line statistics"
  homepage "https://github.com/nodelike/diffloc"
  version "1.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nodelike/diffloc/releases/download/v1.0.7/diffloc_Darwin_x86_64.tar.gz"
      sha256 "8d3ed48da0bdc34f18243f0fb4c18541b8a14f434f83fcc2728b3751f9b289e2"

      def install
        bin.install "diffloc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nodelike/diffloc/releases/download/v1.0.7/diffloc_Darwin_arm64.tar.gz"
      sha256 "d7b82420112d9d2b7ebad83099d79cb3eada31a33f70a589f78a4124d4e8e6f7"

      def install
        bin.install "diffloc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nodelike/diffloc/releases/download/v1.0.7/diffloc_Linux_x86_64.tar.gz"
      sha256 "ac8c5dd79c42481d8c6de54d25a3122ef14f758158d57787e830b0f6faa94d13"
      def install
        bin.install "diffloc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nodelike/diffloc/releases/download/v1.0.7/diffloc_Linux_arm64.tar.gz"
      sha256 "419d5c74730d65ec7899a49f98ed1d14776eaac14d64533f89612b542a5ceacf"
      def install
        bin.install "diffloc"
      end
    end
  end

  test do
    system "#{bin}/diffloc", "--help"
  end
end
