# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffloc < Formula
  desc "Beautiful TUI for git diff line statistics"
  homepage "https://github.com/nodelike/diffloc"
  version "1.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nodelike/diffloc/releases/download/v1.0.8/diffloc_Darwin_x86_64.tar.gz"
      sha256 "c1fee95b862ea8b8a99836f55fee62bb8e2823e86b788f7450b2d64b331739f3"

      define_method(:install) do
        bin.install "diffloc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nodelike/diffloc/releases/download/v1.0.8/diffloc_Darwin_arm64.tar.gz"
      sha256 "9f8d8d077ec4f451f64c551cb4172c74ba9e5b4cb6a45fcfcdd95240970ee318"

      define_method(:install) do
        bin.install "diffloc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nodelike/diffloc/releases/download/v1.0.8/diffloc_Linux_x86_64.tar.gz"
      sha256 "808dcbfc500f636720df86675528744f461417fb64a08759b7d9518674a7eae0"
      define_method(:install) do
        bin.install "diffloc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nodelike/diffloc/releases/download/v1.0.8/diffloc_Linux_arm64.tar.gz"
      sha256 "4168503448d941ebd7e5d33e94c35ff038113c7224debf290813911fa5f434de"
      define_method(:install) do
        bin.install "diffloc"
      end
    end
  end

  test do
    system "#{bin}/diffloc", "--help"
  end
end
